require("dotenv").config();
const pool = require("./poolfile");

let crudsObj = {};

crudsObj.postMonthlyAccountTotal = (
    bi_sum_monthly_account_total_id,
    account_name,
    account_id,
    bi_sum_jan_sub_account_1,
    bi_sum_jan_sub_account_2,
    bi_sum_jan_sub_account_3,
    bi_sum_jan_sub_account_4,
    bi_sum_jan_sub_account_5,
    bi_sum_feb_sub_account_1,
    bi_sum_feb_sub_account_2,
    bi_sum_feb_sub_account_3,
    bi_sum_feb_sub_account_4,
    bi_sum_feb_sub_account_5,
    bi_sum_mar_sub_account_1,
    bi_sum_mar_sub_account_2,
    bi_sum_mar_sub_account_3,
    bi_sum_mar_sub_account_4,
    bi_sum_mar_sub_account_5,
    bi_sum_apr_sub_account_1,
    bi_sum_apr_sub_account_2,
    bi_sum_apr_sub_account_3,
    bi_sum_apr_sub_account_4,
    bi_sum_apr_sub_account_5,
    bi_sum_may_sub_account_1,
    bi_sum_may_sub_account_2,
    bi_sum_may_sub_account_3,
    bi_sum_may_sub_account_4,
    bi_sum_may_sub_account_5,
    bi_sum_jun_sub_account_1,
    bi_sum_jun_sub_account_2,
    bi_sum_jun_sub_account_3,
    bi_sum_jun_sub_account_4,
    bi_sum_jun_sub_account_5,
    bi_sum_jul_sub_account_1,
    bi_sum_jul_sub_account_2,
    bi_sum_jul_sub_account_3,
    bi_sum_jul_sub_account_4,
    bi_sum_jul_sub_account_5,
    bi_sum_aug_sub_account_1,
    bi_sum_aug_sub_account_2,
    bi_sum_aug_sub_account_3,
    bi_sum_aug_sub_account_4,
    bi_sum_aug_sub_account_5,
    bi_sum_sep_sub_account_1,
    bi_sum_sep_sub_account_2,
    bi_sum_sep_sub_account_3,
    bi_sum_sep_sub_account_4,
    bi_sum_sep_sub_account_5,
    bi_sum_oct_sub_account_1,
    bi_sum_oct_sub_account_2,
    bi_sum_oct_sub_account_3,
    bi_sum_oct_sub_account_4,
    bi_sum_oct_sub_account_5,
    bi_sum_nov_sub_account_1,
    bi_sum_nov_sub_account_2,
    bi_sum_nov_sub_account_3,
    bi_sum_nov_sub_account_4,
    bi_sum_nov_sub_account_5,
    bi_sum_dec_sub_account_1,
    bi_sum_dec_sub_account_2,
    bi_sum_dec_sub_account_3,
    bi_sum_dec_sub_account_4,
    bi_sum_dec_sub_account_5,
    company_id,
    account_type
) => {
    return new Promise((resolve, reject) => {
        pool.query(
            `INSERT INTO bi_sums_monthly_account_totals (
         
account_name,
account_id,
bi_sum_jan_sub_account_1,
bi_sum_jan_sub_account_2,
bi_sum_jan_sub_account_3,
bi_sum_jan_sub_account_4,
bi_sum_jan_sub_account_5,
bi_sum_feb_sub_account_1,
bi_sum_feb_sub_account_2,
bi_sum_feb_sub_account_3,
bi_sum_feb_sub_account_4,
bi_sum_feb_sub_account_5,
bi_sum_mar_sub_account_1,
bi_sum_mar_sub_account_2,
bi_sum_mar_sub_account_3,
bi_sum_mar_sub_account_4,
bi_sum_mar_sub_account_5,
bi_sum_apr_sub_account_1,
bi_sum_apr_sub_account_2,
bi_sum_apr_sub_account_3,
bi_sum_apr_sub_account_4,
bi_sum_apr_sub_account_5,
bi_sum_may_sub_account_1,
bi_sum_may_sub_account_2,
bi_sum_may_sub_account_3,
bi_sum_may_sub_account_4,
bi_sum_may_sub_account_5,
bi_sum_jun_sub_account_1,
bi_sum_jun_sub_account_2,
bi_sum_jun_sub_account_3,
bi_sum_jun_sub_account_4,
bi_sum_jun_sub_account_5,
bi_sum_jul_sub_account_1,
bi_sum_jul_sub_account_2,
bi_sum_jul_sub_account_3,
bi_sum_jul_sub_account_4,
bi_sum_jul_sub_account_5,
bi_sum_aug_sub_account_1,
bi_sum_aug_sub_account_2,
bi_sum_aug_sub_account_3,
bi_sum_aug_sub_account_4,
bi_sum_aug_sub_account_5,
bi_sum_sep_sub_account_1,
bi_sum_sep_sub_account_2,
bi_sum_sep_sub_account_3,
bi_sum_sep_sub_account_4,
bi_sum_sep_sub_account_5,
bi_sum_oct_sub_account_1,
bi_sum_oct_sub_account_2,
bi_sum_oct_sub_account_3,
bi_sum_oct_sub_account_4,
bi_sum_oct_sub_account_5,
bi_sum_nov_sub_account_1,
bi_sum_nov_sub_account_2,
bi_sum_nov_sub_account_3,
bi_sum_nov_sub_account_4,
bi_sum_nov_sub_account_5,
bi_sum_dec_sub_account_1,
bi_sum_dec_sub_account_2,
bi_sum_dec_sub_account_3,
bi_sum_dec_sub_account_4,
bi_sum_dec_sub_account_5,
company_id,
account_type
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
                      ?, ?, ?, ?, ?,
                      ?, ?, ?, ?, ?,
                      ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
                      ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
                      ?, ?, ?, ?, ?,
                      ?, ?, ?, ?, ?,
                      ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,
                        ?, ?, ?, ?)`,
            [
                account_name,
                account_id,
                bi_sum_jan_sub_account_1,
                bi_sum_jan_sub_account_2,
                bi_sum_jan_sub_account_3,
                bi_sum_jan_sub_account_4,
                bi_sum_jan_sub_account_5,
                bi_sum_feb_sub_account_1,
                bi_sum_feb_sub_account_2,
                bi_sum_feb_sub_account_3,
                bi_sum_feb_sub_account_4,
                bi_sum_feb_sub_account_5,
                bi_sum_mar_sub_account_1,
                bi_sum_mar_sub_account_2,
                bi_sum_mar_sub_account_3,
                bi_sum_mar_sub_account_4,
                bi_sum_mar_sub_account_5,
                bi_sum_apr_sub_account_1,
                bi_sum_apr_sub_account_2,
                bi_sum_apr_sub_account_3,
                bi_sum_apr_sub_account_4,
                bi_sum_apr_sub_account_5,
                bi_sum_may_sub_account_1,
                bi_sum_may_sub_account_2,
                bi_sum_may_sub_account_3,
                bi_sum_may_sub_account_4,
                bi_sum_may_sub_account_5,
                bi_sum_jun_sub_account_1,
                bi_sum_jun_sub_account_2,
                bi_sum_jun_sub_account_3,
                bi_sum_jun_sub_account_4,
                bi_sum_jun_sub_account_5,
                bi_sum_jul_sub_account_1,
                bi_sum_jul_sub_account_2,
                bi_sum_jul_sub_account_3,
                bi_sum_jul_sub_account_4,
                bi_sum_jul_sub_account_5,
                bi_sum_aug_sub_account_1,
                bi_sum_aug_sub_account_2,
                bi_sum_aug_sub_account_3,
                bi_sum_aug_sub_account_4,
                bi_sum_aug_sub_account_5,
                bi_sum_sep_sub_account_1,
                bi_sum_sep_sub_account_2,
                bi_sum_sep_sub_account_3,
                bi_sum_sep_sub_account_4,
                bi_sum_sep_sub_account_5,
                bi_sum_oct_sub_account_1,
                bi_sum_oct_sub_account_2,
                bi_sum_oct_sub_account_3,
                bi_sum_oct_sub_account_4,
                bi_sum_oct_sub_account_5,
                bi_sum_nov_sub_account_1,
                bi_sum_nov_sub_account_2,
                bi_sum_nov_sub_account_3,
                bi_sum_nov_sub_account_4,
                bi_sum_nov_sub_account_5,
                bi_sum_dec_sub_account_1,
                bi_sum_dec_sub_account_2,
                bi_sum_dec_sub_account_3,
                bi_sum_dec_sub_account_4,
                bi_sum_dec_sub_account_5,
                company_id,
                account_type
            ],
            (err, result) => {
                if (err) {
                    console.error("Database insertion error:", err); // Added error logging
                    return reject(err);
                }
                return resolve({ status: "200", message: "Saving successful", result });
            }
        );
    });
};

crudsObj.getMonthlyAccountTotals = () => {
    return new Promise((resolve, reject) => {
        pool.query("SELECT * FROM bi_sums_monthly_account_totals", (err, results) => {
            if (err) {
                return reject(err);
            }
            return resolve(results);
        });
    });
};

crudsObj.getMonthlyAccountTotalById = (monthly_account_total_id) => {
    return new Promise((resolve, reject) => {
        pool.query(
            "SELECT * FROM bi_sums_monthly_account_totals WHERE bi_sum_monthly_account_total_id = ?",
            [monthly_account_total_id],
            (err, results) => {
                if (err) {
                    return reject(err);
                }
                return resolve(results);
            }
        );
    });
};

crudsObj.updateMonthlyAccountTotal = (bi_sum_monthly_account_total_id, updatedValues) => {
    const {
      
       
        account_name,
account_id,
bi_sum_jan_sub_account_1,
bi_sum_jan_sub_account_2,
bi_sum_jan_sub_account_3,
bi_sum_jan_sub_account_4,
bi_sum_jan_sub_account_5,
bi_sum_feb_sub_account_1,
bi_sum_feb_sub_account_2,
bi_sum_feb_sub_account_3,
bi_sum_feb_sub_account_4,
bi_sum_feb_sub_account_5,
bi_sum_mar_sub_account_1,
bi_sum_mar_sub_account_2,
bi_sum_mar_sub_account_3,
bi_sum_mar_sub_account_4,
bi_sum_mar_sub_account_5,
bi_sum_apr_sub_account_1,
bi_sum_apr_sub_account_2,
bi_sum_apr_sub_account_3,
bi_sum_apr_sub_account_4,
bi_sum_apr_sub_account_5,
bi_sum_may_sub_account_1,
bi_sum_may_sub_account_2,
bi_sum_may_sub_account_3,
bi_sum_may_sub_account_4,
bi_sum_may_sub_account_5,
bi_sum_jun_sub_account_1,
bi_sum_jun_sub_account_2,
bi_sum_jun_sub_account_3,
bi_sum_jun_sub_account_4,
bi_sum_jun_sub_account_5,
bi_sum_jul_sub_account_1,
bi_sum_jul_sub_account_2,
bi_sum_jul_sub_account_3,
bi_sum_jul_sub_account_4,
bi_sum_jul_sub_account_5,
bi_sum_aug_sub_account_1,
bi_sum_aug_sub_account_2,
bi_sum_aug_sub_account_3,
bi_sum_aug_sub_account_4,
bi_sum_aug_sub_account_5,
bi_sum_sep_sub_account_1,
bi_sum_sep_sub_account_2,
bi_sum_sep_sub_account_3,
bi_sum_sep_sub_account_4,
bi_sum_sep_sub_account_5,
bi_sum_oct_sub_account_1,
bi_sum_oct_sub_account_2,
bi_sum_oct_sub_account_3,
bi_sum_oct_sub_account_4,
bi_sum_oct_sub_account_5,
bi_sum_nov_sub_account_1,
bi_sum_nov_sub_account_2,
bi_sum_nov_sub_account_3,
bi_sum_nov_sub_account_4,
bi_sum_nov_sub_account_5,
bi_sum_dec_sub_account_1,
bi_sum_dec_sub_account_2,
bi_sum_dec_sub_account_3,
bi_sum_dec_sub_account_4,
bi_sum_dec_sub_account_5,
company_id,
account_type
    } = updatedValues;

    return new Promise((resolve, reject) => {
        pool.query(
            `UPDATE bi_sums_monthly_account_totals SET 
               account_name=?,
account_id=?,
bi_sum_jan_sub_account_1=?,
bi_sum_jan_sub_account_2=?,
bi_sum_jan_sub_account_3=?,
bi_sum_jan_sub_account_4=?,
bi_sum_jan_sub_account_5=?,
bi_sum_feb_sub_account_1=?,
bi_sum_feb_sub_account_2=?,
bi_sum_feb_sub_account_3=?,
bi_sum_feb_sub_account_4=?,
bi_sum_feb_sub_account_5=?,
bi_sum_mar_sub_account_1=?,
bi_sum_mar_sub_account_2=?,
bi_sum_mar_sub_account_3=?,
bi_sum_mar_sub_account_4=?,
bi_sum_mar_sub_account_5=?,
bi_sum_apr_sub_account_1=?,
bi_sum_apr_sub_account_2=?,
bi_sum_apr_sub_account_3=?,
bi_sum_apr_sub_account_4=?,
bi_sum_apr_sub_account_5=?,
bi_sum_may_sub_account_1=?,
bi_sum_may_sub_account_2=?,
bi_sum_may_sub_account_3=?,
bi_sum_may_sub_account_4=?,
bi_sum_may_sub_account_5=?,
bi_sum_jun_sub_account_1=?,
bi_sum_jun_sub_account_2=?,
bi_sum_jun_sub_account_3=?,
bi_sum_jun_sub_account_4=?,
bi_sum_jun_sub_account_5=?,
bi_sum_jul_sub_account_1=?,
bi_sum_jul_sub_account_2=?,
bi_sum_jul_sub_account_3=?,
bi_sum_jul_sub_account_4=?,
bi_sum_jul_sub_account_5=?,
bi_sum_aug_sub_account_1=?,
bi_sum_aug_sub_account_2=?,
bi_sum_aug_sub_account_3=?,
bi_sum_aug_sub_account_4=?,
bi_sum_aug_sub_account_5=?,
bi_sum_sep_sub_account_1=?,
bi_sum_sep_sub_account_2=?,
bi_sum_sep_sub_account_3=?,
bi_sum_sep_sub_account_4=?,
bi_sum_sep_sub_account_5=?,
bi_sum_oct_sub_account_1=?,
bi_sum_oct_sub_account_2=?,
bi_sum_oct_sub_account_3=?,
bi_sum_oct_sub_account_4=?,
bi_sum_oct_sub_account_5=?,
bi_sum_nov_sub_account_1=?,
bi_sum_nov_sub_account_2=?,
bi_sum_nov_sub_account_3=?,
bi_sum_nov_sub_account_4=?,
bi_sum_nov_sub_account_5=?,
bi_sum_dec_sub_account_1=?,
bi_sum_dec_sub_account_2=?,
bi_sum_dec_sub_account_3=?,
bi_sum_dec_sub_account_4=?,
bi_sum_dec_sub_account_5=?,
company_id=?,
account_type=? 
            WHERE bi_sum_monthly_account_total_id = ?`,
            [
               
                account_name,
                account_id,
                bi_sum_jan_sub_account_1,
                bi_sum_jan_sub_account_2,
                bi_sum_jan_sub_account_3,
                bi_sum_jan_sub_account_4,
                bi_sum_jan_sub_account_5,
                bi_sum_feb_sub_account_1,
                bi_sum_feb_sub_account_2,
                bi_sum_feb_sub_account_3,
                bi_sum_feb_sub_account_4,
                bi_sum_feb_sub_account_5,
                bi_sum_mar_sub_account_1,
                bi_sum_mar_sub_account_2,
                bi_sum_mar_sub_account_3,
                bi_sum_mar_sub_account_4,
                bi_sum_mar_sub_account_5,
                bi_sum_apr_sub_account_1,
                bi_sum_apr_sub_account_2,
                bi_sum_apr_sub_account_3,
                bi_sum_apr_sub_account_4,
                bi_sum_apr_sub_account_5,
                bi_sum_may_sub_account_1,
                bi_sum_may_sub_account_2,
                bi_sum_may_sub_account_3,
                bi_sum_may_sub_account_4,
                bi_sum_may_sub_account_5,
                bi_sum_jun_sub_account_1,
                bi_sum_jun_sub_account_2,
                bi_sum_jun_sub_account_3,
                bi_sum_jun_sub_account_4,
                bi_sum_jun_sub_account_5,
                bi_sum_jul_sub_account_1,
                bi_sum_jul_sub_account_2,
                bi_sum_jul_sub_account_3,
                bi_sum_jul_sub_account_4,
                bi_sum_jul_sub_account_5,
                bi_sum_aug_sub_account_1,
                bi_sum_aug_sub_account_2,
                bi_sum_aug_sub_account_3,
                bi_sum_aug_sub_account_4,
                bi_sum_aug_sub_account_5,
                bi_sum_sep_sub_account_1,
                bi_sum_sep_sub_account_2,
                bi_sum_sep_sub_account_3,
                bi_sum_sep_sub_account_4,
                bi_sum_sep_sub_account_5,
                bi_sum_oct_sub_account_1,
                bi_sum_oct_sub_account_2,
                bi_sum_oct_sub_account_3,
                bi_sum_oct_sub_account_4,
                bi_sum_oct_sub_account_5,
                bi_sum_nov_sub_account_1,
                bi_sum_nov_sub_account_2,
                bi_sum_nov_sub_account_3,
                bi_sum_nov_sub_account_4,
                bi_sum_nov_sub_account_5,
                bi_sum_dec_sub_account_1,
                bi_sum_dec_sub_account_2,
                bi_sum_dec_sub_account_3,
                bi_sum_dec_sub_account_4,
                bi_sum_dec_sub_account_5,
                company_id,
                account_type,
                bi_sum_monthly_account_total_id
            ],
            (err, result) => {
                if (err) {
                    return reject(err);
                }
                return resolve({ status: "200", message: "Update successful", result });
            }
        );
    });
};

crudsObj.deleteMonthlyAccountTotal = (id) => {
    return new Promise((resolve, reject) => {
        pool.query(
            "DELETE FROM bi_sums_monthly_account_totals WHERE bi_sum_monthly_account_total_id = ?",
            [id],
            (err, results) => {
                if (err) {
                    return reject(err);
                }
                return resolve(results);
            }
        );
    });
};

module.exports = crudsObj;